### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by Envek**
First of all, thank you for this small but very useful library. It made my life a bit easier.

I don't want to keep typings for dependencies in my repo. So I propose to put it here so it can work out of the box with any TS project.

### CODE REVIEW

**Comment by deepakjois** [comment]
I have merged the pull request. 

Just a warning. I haven't worked on this package for a long time, and it seems that some dependencies have security vulnerabilities. I don't have the bandwidth to upgrade the packages right now. But if you are actively using this package and have the time, I am happy to merge any pull requests, or even add you as a contributor.

Screen Shot 2021-04-15 at 9 23 06 AM

**Comment by Envek** [comment]
> it seems that some dependencies have security vulnerabilities. 

These dependencies are dev dependencies (this package doesn't have any runtime dependencies), so it doesn't affect its usage in applications.

**Comment by Envek** [comment]
Can you please publish new version with typings to npm?

**Comment by deepakjois** [comment]
I will try to do it in the next week. I don't have a node setup on my laptop at the moment.

Please feel free to ping this issue if I don't get around to it.

**Pull request merged**
